### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Pres26** [sn0wyQ/SQ-Project-CSGO-Arduino#3]
Can you make a video explaining how to do it in detail for those who don't know arduino like me?

**Comment by sn0wyQ** [comment]
I'll do it as soon as project is ready (a week from now maybe?).

By the way, this project is designed with studying purposes only, so if you plan to use it in competitive games ~~it is perfectly okay with me, but you'll be hated by community~~ you basically shouldn't do it

**Comment by Pres26** [comment]
thank you for your feedback your project looks good thanks to your project people can improve themselves good luck

**Comment by Pres26** [comment]
How is your project going, when will you share a video and when you do can you post a link here?

**Comment by sn0wyQ** [comment]
Hi again! Thank you for being interested in this project. As you can see just a couple of days ago I added working aimbot and right now a couple of aimbot features are ready to be merged to master branch.

Unfortunately for last 10 days I was abroad and didn't have enough time to finish what I wish to be in release version 1.0. I hope that I will have enough free time to finish it this week

**Comment by Pres26** [comment]
I understand, thank you, I hope your project will be completed as you want and you will succeed as soon as possible.
